version: "2"
checks:
  complex-logic:
    config:
      threshold: 8
  method-complexity:
    config:
      threshold: 8
plugins:
  duplication:
    enabled: true
    config:
      languages:
      - python
  fixme:
    enabled: true
