[tool.poetry]
name = "podcast-archiver"
version = "0.1.0"
description = "Archive all of your favourite podcasts"
authors = ["Jan Willhaus <mail@janwillhaus.de>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.6"
feedparser = ">=5.2.1,<5.3"
tqdm = "^4.31"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"

[tool.black]
line-length = 88
include = '\.pyi?$'
exclude = '''
/(
    \.git
  | \.venv
  | build
  | dist
)/
'''
